import 'wallet_entity.dart';

final _walletSeedCreatedAt = DateTime.fromMillisecondsSinceEpoch(
  0,
  isUtc: true,
);

final defaultWallets = <WalletEntity>[
  WalletEntity(
    id: 0,
    name: 'Cash',
    type: WalletType.cash,
    emoji: '💵',
    initialBalance: 0,
    currentBalance: 0,
    accountNumber: null,
    note: null,
    sortOrder: 1,
    isArchived: false,
    createdAt: _walletSeedCreatedAt,
    updatedAt: _walletSeedCreatedAt,
  ),
  WalletEntity(
    id: 0,
    name: 'bKash',
    type: WalletType.bkash,
    emoji: '📱',
    initialBalance: 0,
    currentBalance: 0,
    accountNumber: null,
    note: null,
    sortOrder: 2,
    isArchived: false,
    createdAt: _walletSeedCreatedAt,
    updatedAt: _walletSeedCreatedAt,
  ),
  WalletEntity(
    id: 0,
    name: 'Nagad',
    type: WalletType.nagad,
    emoji: '📲',
    initialBalance: 0,
    currentBalance: 0,
    accountNumber: null,
    note: null,
    sortOrder: 3,
    isArchived: false,
    createdAt: _walletSeedCreatedAt,
    updatedAt: _walletSeedCreatedAt,
  ),
  WalletEntity(
    id: 0,
    name: 'Bank Account',
    type: WalletType.bank,
    emoji: '🏦',
    initialBalance: 0,
    currentBalance: 0,
    accountNumber: null,
    note: null,
    sortOrder: 4,
    isArchived: false,
    createdAt: _walletSeedCreatedAt,
    updatedAt: _walletSeedCreatedAt,
  ),
];
